from TASK1.models.schemas import Incident as Task1Incident
from TASK2.models.schemas import Incident as Task2Incident
from TASK2.orchestrator.investigation import investigate_incident


def convert_incident(task1_incident: Task1Incident) -> Task2Incident:
    """
    Convert the TASK1 incident model into the
    existing TASK2 incident model.

    TASK1 remains unchanged.
    TASK2 remains unchanged.
    """

    return Task2Incident(
        incident_id=task1_incident.incident_id,

        service={
            "name": task1_incident.service_name,
            "version": task1_incident.service_version,
        },

        severity=task1_incident.severity.value,

        detected_at=task1_incident.detected_at.isoformat(),

        symptom={
            "description": task1_incident.symptom,
            "baseline_latency_ms": task1_incident.baseline_latency_ms,
            "current_latency_ms": task1_incident.current_latency_ms,
            "increase_percent": task1_incident.increase_percent,
        },

        environment=task1_incident.environment,
    )


def investigate_task1_incident(task1_incident: Task1Incident):
    """
    Run the existing TASK2 investigation using
    an incident generated by TASK1.
    """

    task2_incident = convert_incident(task1_incident)

    return investigate_incident(task2_incident)